#!/bin/bash
#code by tech cochi
clear
bash logo
sleep 5
xdg-open https://t.me/Litecoin_click_bot?start=aH4M
sleep 20
echo " wait 20 second "
pip install -r requirements.txt
unzip session.zip
unzip telethon.zip
clear
bash logo
echo ""
echo ""
echo ""
ls

